"""baseline schema

Revision ID: 69cbe6e11c32
Revises: 
Create Date: 2026-06-02 19:33:31.637536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69cbe6e11c32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohortes_semillero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('anio_edicion', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cupo', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohortes_semillero_id'), 'cohortes_semillero', ['id'], unique=False)
    op.create_table('eventos_fomento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('anio_edicion', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('bases_condiciones_path', sa.String(length=500), nullable=True),
    sa.Column('presupuesto_global', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_fomento_id'), 'eventos_fomento', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_rol'), 'roles', ['rol'], unique=True)
    op.create_table('token_recovery',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('new_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_recovery_id'), 'token_recovery', ['id'], unique=False)
    op.create_index(op.f('ix_token_recovery_token_payload'), 'token_recovery', ['token_payload'], unique=True)
    op.create_index(op.f('ix_token_recovery_user_id'), 'token_recovery', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('asociaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nombre_asociacion', sa.String(length=255), nullable=True),
    sa.Column('anio_creacion', sa.Integer(), nullable=True),
    sa.Column('personeria_juridica', sa.String(length=10), nullable=True),
    sa.Column('tipo_personeria', sa.String(length=50), nullable=True),
    sa.Column('otra_personeria', sa.String(length=100), nullable=True),
    sa.Column('cuit', sa.String(length=15), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('web', sa.String(length=500), nullable=True),
    sa.Column('nombre_referente', sa.String(length=200), nullable=True),
    sa.Column('rol_referente', sa.String(length=100), nullable=True),
    sa.Column('telefono_referente', sa.String(length=30), nullable=True),
    sa.Column('email_referente', sa.String(length=255), nullable=True),
    sa.Column('ambito_produccion', sa.Boolean(), nullable=True),
    sa.Column('ambito_formacion', sa.Boolean(), nullable=True),
    sa.Column('ambito_exhibicion', sa.Boolean(), nullable=True),
    sa.Column('ambito_comunicacion', sa.Boolean(), nullable=True),
    sa.Column('ambito_distribucion', sa.Boolean(), nullable=True),
    sa.Column('ambito_comunidad', sa.Boolean(), nullable=True),
    sa.Column('ambito_investigacion', sa.Boolean(), nullable=True),
    sa.Column('ambito_otro', sa.Boolean(), nullable=True),
    sa.Column('otro_ambito', sa.String(length=255), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('cantidad_integrantes', sa.Integer(), nullable=True),
    sa.Column('articulo_iaavim', sa.String(length=10), nullable=True),
    sa.Column('descripcion_articulacion', sa.Text(), nullable=True),
    sa.Column('info_adicional_integrantes', sa.Text(), nullable=True),
    sa.Column('acta_constitucion_path', sa.String(length=500), nullable=True),
    sa.Column('declaracion_objetivos_path', sa.String(length=500), nullable=True),
    sa.Column('consentimiento', sa.Boolean(), nullable=False),
    sa.Column('declaracion_inicial', sa.Boolean(), nullable=False),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_asociaciones_id'), 'asociaciones', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('estudiantes_esa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('cuil', sa.String(length=15), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=20), nullable=True),
    sa.Column('institucion', sa.String(length=255), nullable=True),
    sa.Column('otra_institucion', sa.String(length=255), nullable=True),
    sa.Column('carrera', sa.String(length=255), nullable=True),
    sa.Column('anio_cursado', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.String(length=20), nullable=True),
    sa.Column('areas_interes', sa.JSON(), nullable=True),
    sa.Column('otra_area', sa.String(length=255), nullable=True),
    sa.Column('participo_proyecto', sa.Boolean(), nullable=True),
    sa.Column('descripcion_experiencia', sa.Text(), nullable=True),
    sa.Column('estudiante_activo', sa.Boolean(), nullable=False),
    sa.Column('leyo_reglamento', sa.Boolean(), nullable=False),
    sa.Column('no_inscripto_repa', sa.Boolean(), nullable=False),
    sa.Column('vigencia_un_anio', sa.Boolean(), nullable=False),
    sa.Column('autoriza_datos', sa.Boolean(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuil'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_estudiantes_esa_id'), 'estudiantes_esa', ['id'], unique=False)
    op.create_table('evaluadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('provincia_pais', sa.String(length=100), nullable=True),
    sa.Column('vinculo_repa', sa.String(length=100), nullable=True),
    sa.Column('formacion_academica', sa.Text(), nullable=True),
    sa.Column('experiencia_audiovisual', sa.Text(), nullable=True),
    sa.Column('areas_especializacion', sa.JSON(), nullable=True),
    sa.Column('otra_area_especializacion', sa.String(length=255), nullable=True),
    sa.Column('participacion_jurados', sa.Text(), nullable=True),
    sa.Column('cv_path', sa.String(length=500), nullable=True),
    sa.Column('especialidades', sa.JSON(), nullable=True),
    sa.Column('roles_habilitados', sa.JSON(), nullable=True),
    sa.Column('edicion_linea_evaluada', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('disponible_convocatorias', sa.Boolean(), nullable=True),
    sa.Column('tipos_convocatoria', sa.JSON(), nullable=True),
    sa.Column('horas_semanales', sa.String(length=20), nullable=True),
    sa.Column('modalidad_preferida', sa.String(length=50), nullable=True),
    sa.Column('emitio_dictamen', sa.Boolean(), nullable=True),
    sa.Column('resolucion_designacion_path', sa.String(length=500), nullable=True),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluadores_id'), 'evaluadores', ['id'], unique=False)
    op.create_table('festivales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('edicion', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=50), nullable=True),
    sa.Column('sedes', sa.JSON(), nullable=True),
    sa.Column('tipo_festival', sa.String(length=50), nullable=True),
    sa.Column('categorias', sa.JSON(), nullable=True),
    sa.Column('tematica', sa.String(length=255), nullable=True),
    sa.Column('cantidad_obras_seleccionadas', sa.Integer(), nullable=True),
    sa.Column('cantidad_obras_misioneras', sa.Integer(), nullable=True),
    sa.Column('cantidad_espectadores', sa.Integer(), nullable=True),
    sa.Column('organizador', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('web', sa.String(length=500), nullable=True),
    sa.Column('periodicidad', sa.String(length=50), nullable=True),
    sa.Column('anio_inicio', sa.Integer(), nullable=True),
    sa.Column('responsable', sa.JSON(), nullable=True),
    sa.Column('curaduria', sa.Boolean(), nullable=True),
    sa.Column('calendario_oficial', sa.Boolean(), nullable=True),
    sa.Column('apoyo_iaavim', sa.Boolean(), nullable=True),
    sa.Column('tipo_apoyo', sa.String(length=255), nullable=True),
    sa.Column('consentimiento', sa.Boolean(), nullable=True),
    sa.Column('desea_recibir_info', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festivales_id'), 'festivales', ['id'], unique=False)
    op.create_table('lineas_fomento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('tope_por_proyecto', sa.Integer(), nullable=True),
    sa.Column('moneda_tope', sa.String(length=10), nullable=True),
    sa.Column('cupo', sa.Integer(), nullable=True),
    sa.Column('requiere_evaluacion', sa.Boolean(), nullable=True),
    sa.Column('tipo_comite', sa.String(length=50), nullable=True),
    sa.Column('documentacion_requerida', sa.JSON(), nullable=True),
    sa.Column('campos_especificos', sa.JSON(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos_fomento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineas_fomento_id'), 'lineas_fomento', ['id'], unique=False)
    op.create_table('obras_audiovisuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('codigo_agam', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('anio_estreno', sa.Integer(), nullable=True),
    sa.Column('anio_ingreso', sa.Integer(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('tipo_produccion', sa.String(length=50), nullable=True),
    sa.Column('extension', sa.String(length=30), nullable=True),
    sa.Column('formato_narrativo', sa.String(length=30), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('subgenero', sa.String(length=100), nullable=True),
    sa.Column('medio', sa.String(length=30), nullable=True),
    sa.Column('formatos_disponibles', sa.JSON(), nullable=True),
    sa.Column('otro_formato', sa.String(length=100), nullable=True),
    sa.Column('resolucion', sa.String(length=20), nullable=True),
    sa.Column('idioma_original', sa.String(length=50), nullable=True),
    sa.Column('subtitulos', sa.String(length=100), nullable=True),
    sa.Column('uso_material', sa.JSON(), nullable=True),
    sa.Column('otro_uso', sa.String(length=255), nullable=True),
    sa.Column('ficha_tecnica_path', sa.String(length=500), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('productora_responsable', sa.String(length=255), nullable=True),
    sa.Column('codigo_repa_productora', sa.String(length=50), nullable=True),
    sa.Column('participo_fomento', sa.String(length=10), nullable=True),
    sa.Column('lineas_fomento', sa.JSON(), nullable=True),
    sa.Column('otro_fomento', sa.String(length=255), nullable=True),
    sa.Column('registro_obra_nacional', sa.String(length=20), nullable=True),
    sa.Column('vinculos_areas', sa.JSON(), nullable=True),
    sa.Column('autoriza_exhibicion', sa.String(length=10), nullable=True),
    sa.Column('autoriza_investigacion', sa.String(length=10), nullable=True),
    sa.Column('convenio_cesion', sa.String(length=10), nullable=True),
    sa.Column('archivo_convenio_path', sa.String(length=500), nullable=True),
    sa.Column('restricciones', sa.Text(), nullable=True),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_agam')
    )
    op.create_index(op.f('ix_obras_audiovisuales_id'), 'obras_audiovisuales', ['id'], unique=False)
    op.create_table('participantes_semillero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohorte_id', sa.Integer(), nullable=False),
    sa.Column('codigo_repa', sa.String(length=50), nullable=True),
    sa.Column('nombre_completo', sa.String(length=255), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('tramites_vinculados', sa.JSON(), nullable=True),
    sa.Column('formacion_previa', sa.Text(), nullable=True),
    sa.Column('proyectos_en_desarrollo', sa.Text(), nullable=True),
    sa.Column('participacion_capacitaciones_iaavim', sa.String(length=20), nullable=True),
    sa.Column('diagnostico_inicial', sa.Text(), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('resultados_cualitativos', sa.Text(), nullable=True),
    sa.Column('resultados_cuantificables', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohorte_id'], ['cohortes_semillero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participantes_semillero_id'), 'participantes_semillero', ['id'], unique=False)
    op.create_table('personas_fisicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('cuil', sa.String(length=15), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=50), nullable=True),
    sa.Column('nivel_educativo', sa.String(length=50), nullable=True),
    sa.Column('trabajo_final', sa.Boolean(), nullable=True),
    sa.Column('titulo_tesis', sa.String(length=255), nullable=True),
    sa.Column('pueblo_originario', sa.String(length=30), nullable=True),
    sa.Column('cual_pueblo', sa.String(length=100), nullable=True),
    sa.Column('afrodescendiente', sa.String(length=30), nullable=True),
    sa.Column('lgbtiq', sa.String(length=30), nullable=True),
    sa.Column('discapacidad', sa.String(length=30), nullable=True),
    sa.Column('tipo_discapacidad', sa.String(length=255), nullable=True),
    sa.Column('personas_a_cargo', sa.Boolean(), nullable=True),
    sa.Column('tipo_personas_a_cargo', sa.JSON(), nullable=True),
    sa.Column('otros_personas_a_cargo', sa.String(length=255), nullable=True),
    sa.Column('principal_fuente_audiovisual', sa.Boolean(), nullable=True),
    sa.Column('otra_fuente', sa.String(length=255), nullable=True),
    sa.Column('relacion_laboral', sa.String(length=50), nullable=True),
    sa.Column('otra_relacion', sa.String(length=255), nullable=True),
    sa.Column('inscripto_afip', sa.String(length=30), nullable=True),
    sa.Column('situacion_iva', sa.String(length=30), nullable=True),
    sa.Column('pertenece_red', sa.Boolean(), nullable=True),
    sa.Column('nombre_red', sa.String(length=255), nullable=True),
    sa.Column('proyectos_iaavim', sa.Boolean(), nullable=True),
    sa.Column('conoce_lineas_fomento', sa.String(length=30), nullable=True),
    sa.Column('interes_formacion', sa.Boolean(), nullable=True),
    sa.Column('areas_capacitacion', sa.Text(), nullable=True),
    sa.Column('interes_difusion', sa.Boolean(), nullable=True),
    sa.Column('interes_experto_iaavim', sa.Boolean(), nullable=True),
    sa.Column('subperfiles_seleccionados', sa.JSON(), nullable=True),
    sa.Column('acepta_terminos', sa.Boolean(), nullable=False),
    sa.Column('portfolio_link', sa.String(length=500), nullable=True),
    sa.Column('sitio_web', sa.String(length=500), nullable=True),
    sa.Column('redes_sociales', sa.JSON(), nullable=True),
    sa.Column('dni_adjunto_path', sa.String(length=500), nullable=True),
    sa.Column('constancia_rentas_path', sa.String(length=500), nullable=True),
    sa.Column('declaracion_inicial', sa.Boolean(), nullable=False),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuil'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_personas_fisicas_id'), 'personas_fisicas', ['id'], unique=False)
    op.create_table('personas_juridicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nombre_pj', sa.String(length=255), nullable=True),
    sa.Column('cuit', sa.String(length=15), nullable=True),
    sa.Column('figura_legal', sa.String(length=50), nullable=True),
    sa.Column('otra_figura_legal', sa.String(length=100), nullable=True),
    sa.Column('fecha_constitucion', sa.Date(), nullable=True),
    sa.Column('objeto_social', sa.Text(), nullable=True),
    sa.Column('domicilio_legal', sa.String(length=255), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=50), nullable=True),
    sa.Column('telefono_institucional', sa.String(length=30), nullable=True),
    sa.Column('email_contacto', sa.String(length=255), nullable=True),
    sa.Column('web_redes', sa.JSON(), nullable=True),
    sa.Column('nombre_representante', sa.String(length=200), nullable=True),
    sa.Column('dni_representante', sa.String(length=20), nullable=True),
    sa.Column('cargo_representante', sa.String(length=100), nullable=True),
    sa.Column('telefono_representante', sa.String(length=30), nullable=True),
    sa.Column('email_representante', sa.String(length=255), nullable=True),
    sa.Column('vincular_personas', sa.String(length=10), nullable=True),
    sa.Column('actividades_principales', sa.JSON(), nullable=True),
    sa.Column('otra_actividad', sa.String(length=255), nullable=True),
    sa.Column('lineas_trabajo', sa.Text(), nullable=True),
    sa.Column('apoyo_iaavim', sa.String(length=10), nullable=True),
    sa.Column('descripcion_apoyo', sa.Text(), nullable=True),
    sa.Column('otros_registros', sa.String(length=10), nullable=True),
    sa.Column('cuales_registros', sa.String(length=255), nullable=True),
    sa.Column('estatuto_path', sa.String(length=500), nullable=True),
    sa.Column('constancia_cuit_path', sa.String(length=500), nullable=True),
    sa.Column('acta_autoridades_path', sa.String(length=500), nullable=True),
    sa.Column('cv_institucional_path', sa.String(length=500), nullable=True),
    sa.Column('consentimiento', sa.Boolean(), nullable=False),
    sa.Column('declaracion_inicial', sa.Boolean(), nullable=False),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_personas_juridicas_id'), 'personas_juridicas', ['id'], unique=False)
    op.create_table('rodajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tipo_registro', sa.String(length=30), nullable=True),
    sa.Column('titulo_produccion', sa.String(length=255), nullable=True),
    sa.Column('tipo_produccion', sa.String(length=50), nullable=True),
    sa.Column('otro_tipo_produccion', sa.String(length=100), nullable=True),
    sa.Column('genero', sa.String(length=100), nullable=True),
    sa.Column('clasificacion', sa.String(length=50), nullable=True),
    sa.Column('otra_clasificacion', sa.String(length=100), nullable=True),
    sa.Column('pais_produccion', sa.String(length=100), nullable=True),
    sa.Column('idioma_original', sa.String(length=50), nullable=True),
    sa.Column('sinopsis', sa.Text(), nullable=True),
    sa.Column('anio_rodaje', sa.Integer(), nullable=True),
    sa.Column('codigo_repa_productora', sa.String(length=50), nullable=True),
    sa.Column('codigos_repa_responsables', sa.JSON(), nullable=True),
    sa.Column('id_proyecto_fomento', sa.String(length=50), nullable=True),
    sa.Column('nombre_productora', sa.String(length=255), nullable=True),
    sa.Column('cuit_productora', sa.String(length=13), nullable=True),
    sa.Column('representante_legal', sa.String(length=200), nullable=True),
    sa.Column('productor_campo', sa.String(length=200), nullable=True),
    sa.Column('email_productora', sa.String(length=255), nullable=True),
    sa.Column('telefono_productora', sa.String(length=50), nullable=True),
    sa.Column('provincia_pais_origen', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio_rodaje', sa.Date(), nullable=True),
    sa.Column('fecha_fin_rodaje', sa.Date(), nullable=True),
    sa.Column('locaciones', sa.JSON(), nullable=True),
    sa.Column('cantidad_permisos', sa.Integer(), nullable=True),
    sa.Column('vehiculos_equipamiento', sa.Text(), nullable=True),
    sa.Column('requiere_carta_aval', sa.Boolean(), nullable=True),
    sa.Column('destino_aval', sa.String(length=50), nullable=True),
    sa.Column('otro_destino_aval', sa.String(length=100), nullable=True),
    sa.Column('motivo_aval', sa.Text(), nullable=True),
    sa.Column('fecha_limite_aval', sa.Date(), nullable=True),
    sa.Column('tiene_poliza_seguro', sa.Boolean(), nullable=True),
    sa.Column('tiene_acuerdo_indemnizacion', sa.Boolean(), nullable=True),
    sa.Column('tiene_autorizaciones_privados', sa.Boolean(), nullable=True),
    sa.Column('tiene_fotos_locaciones', sa.Boolean(), nullable=True),
    sa.Column('tiene_permisos_especiales', sa.Boolean(), nullable=True),
    sa.Column('documentos_adjuntos', sa.JSON(), nullable=True),
    sa.Column('fecha_real_finalizacion', sa.Date(), nullable=True),
    sa.Column('cantidad_tecnicos_locales', sa.Integer(), nullable=True),
    sa.Column('cantidad_artistas_locales', sa.Integer(), nullable=True),
    sa.Column('descripcion_beneficios_locales', sa.Text(), nullable=True),
    sa.Column('medidas_ambientales', sa.Text(), nullable=True),
    sa.Column('compromisos_comunitarios', sa.Text(), nullable=True),
    sa.Column('informe_rodaje', sa.String(length=500), nullable=True),
    sa.Column('estado_tramite', sa.String(length=30), nullable=True),
    sa.Column('fecha_evaluacion', sa.Date(), nullable=True),
    sa.Column('fecha_emision_permiso', sa.Date(), nullable=True),
    sa.Column('tarifas_aplicadas', sa.Text(), nullable=True),
    sa.Column('pagos_realizados', sa.Text(), nullable=True),
    sa.Column('inspector_asignado', sa.String(length=200), nullable=True),
    sa.Column('informe_inspeccion', sa.Text(), nullable=True),
    sa.Column('observaciones_internas', sa.Text(), nullable=True),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rodajes_id'), 'rodajes', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('tipo_sala', sa.String(length=50), nullable=True),
    sa.Column('otro_tipo', sa.String(length=100), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=50), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('tiene_proyector_digital', sa.Boolean(), nullable=True),
    sa.Column('tiene_proyector_35mm', sa.Boolean(), nullable=True),
    sa.Column('tiene_sonido_dolby', sa.Boolean(), nullable=True),
    sa.Column('tiene_accesibilidad', sa.Boolean(), nullable=True),
    sa.Column('otras_caracteristicas', sa.Text(), nullable=True),
    sa.Column('nombre_responsable', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('web', sa.String(length=500), nullable=True),
    sa.Column('responsable_legal', sa.JSON(), nullable=True),
    sa.Column('programador', sa.JSON(), nullable=True),
    sa.Column('responsable_tecnico', sa.JSON(), nullable=True),
    sa.Column('afiliaciones', sa.JSON(), nullable=True),
    sa.Column('consentimiento', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salas_id'), 'salas', ['id'], unique=False)
    op.create_table('tramites_fomento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tipo_tramite', sa.String(length=50), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('linea_id', sa.Integer(), nullable=True),
    sa.Column('cohorte_semillero_id', sa.Integer(), nullable=True),
    sa.Column('codigo_repa_presentante', sa.String(length=50), nullable=True),
    sa.Column('tipo_productora', sa.String(length=50), nullable=True),
    sa.Column('distrito_presentante', sa.String(length=50), nullable=True),
    sa.Column('contacto_email', sa.String(length=255), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=30), nullable=True),
    sa.Column('titulo_proyecto', sa.String(length=255), nullable=True),
    sa.Column('medio', sa.String(length=50), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('extension', sa.String(length=30), nullable=True),
    sa.Column('formato_narrativo', sa.String(length=30), nullable=True),
    sa.Column('duracion_estimada_min', sa.Integer(), nullable=True),
    sa.Column('sinopsis', sa.Text(), nullable=True),
    sa.Column('subgenero', sa.String(length=100), nullable=True),
    sa.Column('etapa', sa.String(length=50), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('idioma_original', sa.String(length=50), nullable=True),
    sa.Column('moneda_principal', sa.String(length=10), nullable=True),
    sa.Column('presupuesto_total', sa.Integer(), nullable=True),
    sa.Column('monto_solicitado_iaavim', sa.Integer(), nullable=True),
    sa.Column('monto_aprobado_iaavim', sa.Integer(), nullable=True),
    sa.Column('aporte_privado_monto', sa.Integer(), nullable=True),
    sa.Column('aporte_privado_fuente', sa.String(length=255), nullable=True),
    sa.Column('otros_aportes_no_iaavim', sa.JSON(), nullable=True),
    sa.Column('aportes_en_especie', sa.Text(), nullable=True),
    sa.Column('monto_estimado_reintegro', sa.Integer(), nullable=True),
    sa.Column('gastos_elegibles', sa.Text(), nullable=True),
    sa.Column('montos_invertidos_provincia', sa.Integer(), nullable=True),
    sa.Column('distritos_rodaje', sa.JSON(), nullable=True),
    sa.Column('fechas_rodaje', sa.JSON(), nullable=True),
    sa.Column('postulante_linea_nacional', sa.String(length=255), nullable=True),
    sa.Column('postulante_linea_misionera', sa.String(length=255), nullable=True),
    sa.Column('carpeta_dossier_path', sa.String(length=500), nullable=True),
    sa.Column('presupuesto_detallado_path', sa.String(length=500), nullable=True),
    sa.Column('plan_financiamiento_path', sa.String(length=500), nullable=True),
    sa.Column('anexos_tecnicos_path', sa.String(length=500), nullable=True),
    sa.Column('otros_documentos', sa.JSON(), nullable=True),
    sa.Column('estado_tramite', sa.String(length=50), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('fecha_dictamen', sa.DateTime(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('pendiente_juridico', sa.Boolean(), nullable=True),
    sa.Column('motivo_juridico', sa.String(length=255), nullable=True),
    sa.Column('fecha_pendiente_juridico', sa.DateTime(), nullable=True),
    sa.Column('pendiente_administracion', sa.Boolean(), nullable=True),
    sa.Column('motivo_administracion', sa.String(length=255), nullable=True),
    sa.Column('fecha_pendiente_administracion', sa.DateTime(), nullable=True),
    sa.Column('pendiente_agam', sa.Boolean(), nullable=True),
    sa.Column('motivo_agam', sa.String(length=255), nullable=True),
    sa.Column('fecha_pendiente_agam', sa.DateTime(), nullable=True),
    sa.Column('comite_asignado_id', sa.Integer(), nullable=True),
    sa.Column('resolucion_otorgamiento_id', sa.Integer(), nullable=True),
    sa.Column('resolucion_otorgamiento_path', sa.String(length=500), nullable=True),
    sa.Column('convenio_path', sa.String(length=500), nullable=True),
    sa.Column('nro_expediente', sa.String(length=50), nullable=True),
    sa.Column('pagos', sa.JSON(), nullable=True),
    sa.Column('rendicion_estado', sa.String(length=50), nullable=True),
    sa.Column('estado_agam', sa.String(length=50), nullable=True),
    sa.Column('fecha_entrega_copia', sa.DateTime(), nullable=True),
    sa.Column('acta_recepcion_path', sa.String(length=500), nullable=True),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tramites_fomento_id'), 'tramites_fomento', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('acompanamientos_semillero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('responsable', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('adjuntos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes_semillero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acompanamientos_semillero_id'), 'acompanamientos_semillero', ['id'], unique=False)
    op.create_table('comites_fomento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('integrantes', sa.JSON(), nullable=True),
    sa.Column('resolucion_designacion_path', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos_fomento.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['lineas_fomento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comites_fomento_id'), 'comites_fomento', ['id'], unique=False)
    op.create_table('equipo_tecnico_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('en_repa', sa.String(length=10), nullable=True),
    sa.Column('codigo_repa', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras_audiovisuales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipo_tecnico_obra_id'), 'equipo_tecnico_obra', ['id'], unique=False)
    op.create_table('exhibiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.Column('titulo_obra', sa.String(length=255), nullable=True),
    sa.Column('fecha_exhibicion', sa.Date(), nullable=True),
    sa.Column('cantidad_funciones', sa.Integer(), nullable=True),
    sa.Column('tipo_exhibicion', sa.String(length=50), nullable=True),
    sa.Column('nombre_evento', sa.String(length=255), nullable=True),
    sa.Column('espectadores_total', sa.Integer(), nullable=True),
    sa.Column('espectadores_pagos', sa.Integer(), nullable=True),
    sa.Column('espectadores_gratuitos', sa.Integer(), nullable=True),
    sa.Column('espectadores_abonados', sa.Integer(), nullable=True),
    sa.Column('recaudacion_total', sa.Float(), nullable=True),
    sa.Column('precio_entrada_general', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('borrador', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras_audiovisuales.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exhibiciones_id'), 'exhibiciones', ['id'], unique=False)
    op.create_table('integrantes_asociacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asociacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('vinculado_repa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asociacion_id'], ['asociaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrantes_asociacion_id'), 'integrantes_asociacion', ['id'], unique=False)
    op.create_table('integrantes_pj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_juridica_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('vinculado_repa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['persona_juridica_id'], ['personas_juridicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrantes_pj_id'), 'integrantes_pj', ['id'], unique=False)
    op.create_table('subperfil_capacitador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_fisica_id', sa.Integer(), nullable=False),
    sa.Column('capacitaciones_iaavim', sa.Boolean(), nullable=True),
    sa.Column('capacitaciones', sa.JSON(), nullable=True),
    sa.Column('capacitador_actual', sa.Boolean(), nullable=True),
    sa.Column('areas_capacitacion', sa.Text(), nullable=True),
    sa.Column('publico_destinatario', sa.String(length=255), nullable=True),
    sa.Column('tipos_instituciones', sa.JSON(), nullable=True),
    sa.Column('disena_contenidos', sa.Boolean(), nullable=True),
    sa.Column('interes_lista_expertos', sa.Boolean(), nullable=True),
    sa.Column('cv_link', sa.String(length=500), nullable=True),
    sa.Column('materiales_link', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['persona_fisica_id'], ['personas_fisicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_fisica_id')
    )
    op.create_index(op.f('ix_subperfil_capacitador_id'), 'subperfil_capacitador', ['id'], unique=False)
    op.create_table('subperfil_director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_fisica_id', sa.Integer(), nullable=False),
    sa.Column('titulo_obra', sa.String(length=255), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['persona_fisica_id'], ['personas_fisicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subperfil_director_id'), 'subperfil_director', ['id'], unique=False)
    op.create_table('subperfil_documentalista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_fisica_id', sa.Integer(), nullable=False),
    sa.Column('titulo_obra', sa.String(length=255), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['persona_fisica_id'], ['personas_fisicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subperfil_documentalista_id'), 'subperfil_documentalista', ['id'], unique=False)
    op.create_table('subperfil_guionista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_fisica_id', sa.Integer(), nullable=False),
    sa.Column('titulo_obra', sa.String(length=255), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['persona_fisica_id'], ['personas_fisicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subperfil_guionista_id'), 'subperfil_guionista', ['id'], unique=False)
    op.create_table('subperfil_investigador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_fisica_id', sa.Integer(), nullable=False),
    sa.Column('participo_proyectos', sa.Boolean(), nullable=True),
    sa.Column('proyectos', sa.JSON(), nullable=True),
    sa.Column('tiene_publicaciones', sa.Boolean(), nullable=True),
    sa.Column('publicaciones_link', sa.String(length=500), nullable=True),
    sa.Column('tematica_principal', sa.String(length=255), nullable=True),
    sa.Column('enfoque', sa.String(length=255), nullable=True),
    sa.Column('pertenece_grupo', sa.Boolean(), nullable=True),
    sa.Column('nombre_grupo', sa.String(length=255), nullable=True),
    sa.Column('recibio_financiamiento', sa.Boolean(), nullable=True),
    sa.Column('institucion_financiamiento', sa.String(length=255), nullable=True),
    sa.Column('interes_red_investigadores', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['persona_fisica_id'], ['personas_fisicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_fisica_id')
    )
    op.create_index(op.f('ix_subperfil_investigador_id'), 'subperfil_investigador', ['id'], unique=False)
    op.create_table('subperfil_productor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_fisica_id', sa.Integer(), nullable=False),
    sa.Column('titulo_obra', sa.String(length=255), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['persona_fisica_id'], ['personas_fisicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subperfil_productor_id'), 'subperfil_productor', ['id'], unique=False)
    op.create_table('subperfil_realizador_integral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_fisica_id', sa.Integer(), nullable=False),
    sa.Column('titulo_obra', sa.String(length=255), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['persona_fisica_id'], ['personas_fisicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subperfil_realizador_integral_id'), 'subperfil_realizador_integral', ['id'], unique=False)
    op.create_table('subperfil_tecnico_artistico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_fisica_id', sa.Integer(), nullable=False),
    sa.Column('areas', sa.JSON(), nullable=True),
    sa.Column('medios', sa.JSON(), nullable=True),
    sa.Column('obras_iaavim', sa.JSON(), nullable=True),
    sa.Column('especializaciones', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['persona_fisica_id'], ['personas_fisicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_fisica_id')
    )
    op.create_index(op.f('ix_subperfil_tecnico_artistico_id'), 'subperfil_tecnico_artistico', ['id'], unique=False)
    op.create_table('dictamenes_fomento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tramite_id', sa.Integer(), nullable=False),
    sa.Column('comite_id', sa.Integer(), nullable=True),
    sa.Column('evaluador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_dictamen', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('puntaje', sa.Integer(), nullable=True),
    sa.Column('archivo_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('devolucion_presentante', sa.Boolean(), nullable=True),
    sa.Column('devolucion_archivo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comite_id'], ['comites_fomento.id'], ),
    sa.ForeignKeyConstraint(['evaluador_id'], ['evaluadores.id'], ),
    sa.ForeignKeyConstraint(['tramite_id'], ['tramites_fomento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictamenes_fomento_id'), 'dictamenes_fomento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictamenes_fomento_id'), table_name='dictamenes_fomento')
    op.drop_table('dictamenes_fomento')
    op.drop_index(op.f('ix_subperfil_tecnico_artistico_id'), table_name='subperfil_tecnico_artistico')
    op.drop_table('subperfil_tecnico_artistico')
    op.drop_index(op.f('ix_subperfil_realizador_integral_id'), table_name='subperfil_realizador_integral')
    op.drop_table('subperfil_realizador_integral')
    op.drop_index(op.f('ix_subperfil_productor_id'), table_name='subperfil_productor')
    op.drop_table('subperfil_productor')
    op.drop_index(op.f('ix_subperfil_investigador_id'), table_name='subperfil_investigador')
    op.drop_table('subperfil_investigador')
    op.drop_index(op.f('ix_subperfil_guionista_id'), table_name='subperfil_guionista')
    op.drop_table('subperfil_guionista')
    op.drop_index(op.f('ix_subperfil_documentalista_id'), table_name='subperfil_documentalista')
    op.drop_table('subperfil_documentalista')
    op.drop_index(op.f('ix_subperfil_director_id'), table_name='subperfil_director')
    op.drop_table('subperfil_director')
    op.drop_index(op.f('ix_subperfil_capacitador_id'), table_name='subperfil_capacitador')
    op.drop_table('subperfil_capacitador')
    op.drop_index(op.f('ix_integrantes_pj_id'), table_name='integrantes_pj')
    op.drop_table('integrantes_pj')
    op.drop_index(op.f('ix_integrantes_asociacion_id'), table_name='integrantes_asociacion')
    op.drop_table('integrantes_asociacion')
    op.drop_index(op.f('ix_exhibiciones_id'), table_name='exhibiciones')
    op.drop_table('exhibiciones')
    op.drop_index(op.f('ix_equipo_tecnico_obra_id'), table_name='equipo_tecnico_obra')
    op.drop_table('equipo_tecnico_obra')
    op.drop_index(op.f('ix_comites_fomento_id'), table_name='comites_fomento')
    op.drop_table('comites_fomento')
    op.drop_index(op.f('ix_acompanamientos_semillero_id'), table_name='acompanamientos_semillero')
    op.drop_table('acompanamientos_semillero')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tramites_fomento_id'), table_name='tramites_fomento')
    op.drop_table('tramites_fomento')
    op.drop_index(op.f('ix_salas_id'), table_name='salas')
    op.drop_table('salas')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_rodajes_id'), table_name='rodajes')
    op.drop_table('rodajes')
    op.drop_index(op.f('ix_personas_juridicas_id'), table_name='personas_juridicas')
    op.drop_table('personas_juridicas')
    op.drop_index(op.f('ix_personas_fisicas_id'), table_name='personas_fisicas')
    op.drop_table('personas_fisicas')
    op.drop_index(op.f('ix_participantes_semillero_id'), table_name='participantes_semillero')
    op.drop_table('participantes_semillero')
    op.drop_index(op.f('ix_obras_audiovisuales_id'), table_name='obras_audiovisuales')
    op.drop_table('obras_audiovisuales')
    op.drop_index(op.f('ix_lineas_fomento_id'), table_name='lineas_fomento')
    op.drop_table('lineas_fomento')
    op.drop_index(op.f('ix_festivales_id'), table_name='festivales')
    op.drop_table('festivales')
    op.drop_index(op.f('ix_evaluadores_id'), table_name='evaluadores')
    op.drop_table('evaluadores')
    op.drop_index(op.f('ix_estudiantes_esa_id'), table_name='estudiantes_esa')
    op.drop_table('estudiantes_esa')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_asociaciones_id'), table_name='asociaciones')
    op.drop_table('asociaciones')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_recovery_user_id'), table_name='token_recovery')
    op.drop_index(op.f('ix_token_recovery_token_payload'), table_name='token_recovery')
    op.drop_index(op.f('ix_token_recovery_id'), table_name='token_recovery')
    op.drop_table('token_recovery')
    op.drop_index(op.f('ix_roles_rol'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_eventos_fomento_id'), table_name='eventos_fomento')
    op.drop_table('eventos_fomento')
    op.drop_index(op.f('ix_cohortes_semillero_id'), table_name='cohortes_semillero')
    op.drop_table('cohortes_semillero')
    # ### end Alembic commands ###
